<?php

namespace App\Services\Ingestion;

class TextNormalizer {
    public function normalize(string $rawText): string {
        $ligatureMap = [
            // Standard Unicode ligatures
            "\u{FB00}" => 'ff',
            "\u{FB01}" => 'fi',
            "\u{FB02}" => 'fl',
            "\u{FB03}" => 'ffi',
            "\u{FB04}" => 'ffl',
            // Font-specific PUA characters generated by pdftotext for this PDF
            "\u{E000}" => 'f',
            "\u{E001}" => 'ti',
            "\u{E002}" => 'fl', // Assumed
            "\u{E003}" => 'fi',
        ];
        $rawText = strtr($rawText, $ligatureMap);

        // 0. Hapus karakter form feed (page break dari pdftotext)
        $text = str_replace("\x0C", "", $rawText);
        
        // 1. Gabungkan baris yang terpotong di tengah kalimat
        //    (regex: '/([a-z,])\n(?=[a-z])/u')
        $text = preg_replace('/([a-z,])\n(?=[a-z])/u', '$1 ', $text);
        
        // 2. Normalisasi whitespace ganda/tab/newline berlebih jadi spasi tunggal,
        //    tapi kita mau mempertahankan newline antar paragraf/pasal.
        //    Wait, requirements say: "Normalisasi whitespace ganda/tab jadi spasi tunggal"
        $text = preg_replace('/[ \t]+/', ' ', $text);
        
        // 3. Normalisasi variasi "PASAL"/"pasal" jadi "Pasal" (case-insensitive)
        $text = preg_replace('/(?i)pasal/', 'Pasal', $text);
        
        return $text;
    }
}
